
server:
  port: 8500

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

spring:
  application:
    name: user-service
  #database-config
  datasource:
    url: jdbc:mysql://localhost:3306/cws?useUnicode=true;characterEncoding=utf8;
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false


token:
  expiration_time: 86400000
  secret: dXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2Vu

jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'usertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertokenusertoken'|base64
  secret: dXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2VudXNlcnRva2Vu
  token-validity-in-seconds: 8640000