
server:
  port: 0

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kariseio/spring-cloud-config
#        native:
#          search-locations: file:///Users/dowonlee/Desktop/Work/native-file-repo

